<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>


        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <!-- <TreatWarningsAsErrors>true</TreatWarningsAsErrors> -->
        <Deterministic>true</Deterministic>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <DebugType>portable</DebugType>
        <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
        <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
        <NoWarn>$(NoWarn);NU1603;NU1701</NoWarn> <!-- common NuGet chatter -->
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.5"/>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.8" />
    </ItemGroup>

</Project>